# Generated by Django 6.0.2 on 2026-04-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentitem",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentitem",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="documentitem",
            name="remark",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="documentitem",
            name="row_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentitem",
            name="spec",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="documentitem",
            name="unit",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="documentitem",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.product",
            ),
        ),
        migrations.AlterField(
            model_name="documentitem",
            name="qty",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
