# Generated by Django 6.0.2 on 2026-02-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_warehouse_stockledger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock",
        ),
    ]
