# Generated by Django 6.0.2 on 2026-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_product_stock_remove_productvariant_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="code",
            field=models.CharField(default="YYCOM_MAIN", max_length=50, unique=True),
        ),
    ]
