# Generated by Django 6.0.2 on 2026-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("category_name", models.CharField(max_length=100)),
                (
                    "level",
                    models.IntegerField(choices=[(1, "1차"), (2, "2차"), (3, "3차")]),
                ),
                ("priority", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_IN", "Purchase In"),
                    ("SALE_OUT", "Sale Out"),
                    ("ADJUST", "Adjust"),
                    ("RESERVE", "Reserve"),
                    ("RELEASE", "Release"),
                    ("RETURN", "Return"),
                ],
                max_length=20,
            ),
        ),
    ]
