# Generated by Django 6.0.2 on 2026-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_categoryrule_alter_stockledger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["external_id"], name="catalog_pro_externa_e8c827_idx"
            ),
        ),
    ]
