# Generated by Django 6.0.2 on 2026-03-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="source_category_path",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="source_supplier",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
