# Generated by Django 6.0.2 on 2026-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_product_source_category_path_product_source_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("parent", "slug")},
        ),
    ]
