# Generated by Django 6.0.2 on 2026-03-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_mall_product_mall"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="mpn",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer"], name="catalog_pro_manufac_e16430_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["mpn"], name="catalog_pro_mpn_5ef00f_idx"),
        ),
    ]
