# Generated by Django 6.0.2 on 2026-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_supplier_supplierproduct"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_manufac_e16430_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_mpn_5ef00f_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="serial_number",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer", "mpn"], name="catalog_pro_manufac_31036c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["product"], name="catalog_sup_product_7b69bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(fields=["price"], name="catalog_sup_price_c1c51a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["supplier"], name="catalog_sup_supplie_05faf9_idx"
            ),
        ),
    ]
