# Generated by Django 6.0.2 on 2026-03-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_remove_product_catalog_pro_manufac_e16430_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(db_index=True, max_length=200)),
                ("mpn", models.CharField(db_index=True, max_length=200)),
                ("name", models.CharField(max_length=300)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "unique_together": {("manufacturer", "mpn")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="canonical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.canonicalproduct",
            ),
        ),
    ]
